language: java
jdk:
- oraclejdk8
# git strips the wrapper jar file so we have to force its download during the build

env:
  - spring_profiles_active=dev
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw -Dmaven.javadoc.skip=true clean install -B -V

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 3a013253-cb4a-4714-aa7e-91e5c0dbab9b

cache:
  directories:
  - .autoconf
  - $HOME/.m2
