
spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/catalog?useSSL=false
  username: root
  password: admin
  initialization-mode: always
 jpa:
  hibernate:
   ddl-auto: create-drop
   show-sql: true

hibernate:
 dialect: org.hibernate.dialect.MySQLDialect
 hbm2ddl:
  auto: true