# H2
spring:
 h2:
  console:
   enabled: true
   path: /h2
# Datasource
spring:
 datasource:
  url: jdbc:h2:file:~/test
  username: sa
  password:
  driver-class-name: org.h2.Driver
hibernate:
 dialect: org.hibernate.dialect.H2Dialect