logging:
 level:
  com:
   leanmentors: debug

spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/catalog?useSSL=false
  username: root
  password: admin
  initialization-mode: always
 jpa:
  hibernate.ddl-auto: update
  show-sql: true

hibernate:
 dialect: org.hibernate.dialect.MySQLDialect

#expose all the Actuator endpoints
management:
 endpoints:
  web:
   exposure:
    include: "*"